name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip nkf
      - name: Build
        run: make build-cd
