name: CD

# パーミッションを追加
permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: out/bin/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ./out/bin/admina-sysutils-linux-amd64.zip
            ./out/bin/admina-sysutils-windows-amd64.zip
            ./out/bin/admina-sysutils-darwin-amd64.zip
          fail_on_unmatched_files: true
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
