name: CD

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Build all platforms
        run: make build-all
      - name: Create release archive
        run: tar -czvf admina-sysutils-${{ github.ref_name }}.tar.gz -C bin .
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./admina-sysutils-${{ github.ref_name }}.tar.gz
          asset_name: admina-sysutils-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
