name: CD

# パーミッションを追加
permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: out/bin/
      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/bin/admina-sysutils-linux-amd64.zip
          asset_name: admina-sysutils-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/bin/admina-sysutils-windows-amd64.zip
          asset_name: admina-sysutils-windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload MacOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/bin/admina-sysutils-darwin-amd64.zip
          asset_name: admina-sysutils-darwin-amd64.zip
          asset_content_type: application/zip
