name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for Takumi Guard OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 #v1.1.1
        with:
          bot-id: "BT01KSPTTXMY1DBFSFFSHVGJT8KA"
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Run tests
        env:
          ADMINA_ORGANIZATION_ID: "dummy_organization_id"
          ADMINA_API_KEY: "dummy_api_key"
        run: make test-ci
