name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run tests
        env:
          ADMINA_ORGANIZATION_ID: "dummy_organization_id"
          ADMINA_API_KEY: "dummy_api_key"
        run: make test
